### ISSUE TITLE
Priority Wallbox Datapoints

### ISSUE THREAD

**Issue by ricten** [nobl/ioBroker.senec#46]
// "WALLBOX":{"APPARENT_CHARGING_POWER":"","PROHIBIT_USAGE":"","EV_CONNECTED":"","STATE":""}
form += ',"WALLBOX":{"APPARENT_CHARGING_POWER":"","PROHIBIT_USAGE":"","EV_CONNECTED":"","STATE":""}';

Can you change te Datapoints to priority high. At the Moment i have done for myself in Main.js @line 150 / 160.  @version 1.3.2

edit: insert Version from main.js

**Comment by nobl** [comment]
I strongly suggest to NOT modify priorities, because that can break the SENEC appliance in a way that it will stop communicating with senec and thus could have a negative impact on your warranty.

Nevertheless I am going to implement something in a future release that lets one add additional datapoints for high priority. 
(But again: a single extra datapoint with high priority can break the senec appliance!)

**Comment by nobl** [comment]
v1.3.9

**Comment by nobl** [comment]
Got reverted with v1.5.0 -> use new Configuration dialogue to add them individually.
